### PR TITLE
feat: Backlog/After Effects basic integration

### PR DESCRIPTION
**Pull request by mikedatsik**
Resolves : 

* CLICKUP-
* FT-
* SENTRY-
* ZENDESK-

- [ ] I have added automatic tests where applicable.
- [ ] The PR contains a description of what has been changed.
- [ ] The description contains manual test instructions.
- [ ] The PR contains update to the release notes.
- [ ] The PR contains update to the documentation.

This PR has been tested on :

- [x] Windows.
- [x] MacOs.
- [ ] Linux.

# Overview
Based on Premiere plugin adds After Effects integration with project exporter and publisher.

### CODE REVIEW

**Comment by lluisCM** [comment]
Hello @mikedatsik, thank you for your contribution.
We will now start reviewing it and test it.
FYI we are going to rebase it to the `release/24.11.0` branch as the main branch is not going to be updated anymore until next year, as we are currently working on a restructure of the monorepo and a new version of Connect.

**Comment by mikedatsik** [comment]
Hi @lluisCM, I've added this small requested comments. Thank for quick response.

**Review by lluisCM — DISMISSED** [review]
LGTM

**Review by lluisCM — APPROVED** [review]

**Review by dennisweil — APPROVED** [review]
Good to go :)

**Pull request merged**
